# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x1a\x0btypes.proto2\xc4\x06\n\nBLSSigning\x12\x61\n\x12GenerateKeypairRaw\x12$.bls_proto.GenerateKeypairRequestRaw\x1a%.bls_proto.GenerateKeypairResponseRaw\x12\x61\n\x12GenerateKeypairHex\x12$.bls_proto.GenerateKeypairRequestHex\x1a%.bls_proto.GenerateKeypairResponseHex\x12@\n\x07SignRaw\x12\x19.bls_proto.SignRequestRaw\x1a\x1a.bls_proto.SignResponseRaw\x12@\n\x07SignHex\x12\x19.bls_proto.SignRequestHex\x1a\x1a.bls_proto.SignResponseHex\x12\x43\n\tVerifyRaw\x12\x1b.bls_proto.VerifyRequestRaw\x1a\x19.bls_proto.VerifyResponse\x12\x43\n\tVerifyHex\x12\x1b.bls_proto.VerifyRequestHex\x1a\x19.bls_proto.VerifyResponse\x12O\n\x0c\x41ggregateRaw\x12\x1e.bls_proto.AggregateRequestRaw\x1a\x1f.bls_proto.AggregateResponseRaw\x12O\n\x0c\x41ggregateHex\x12\x1e.bls_proto.AggregateRequestHex\x1a\x1f.bls_proto.AggregateResponseHex\x12_\n\x13VerifyAggregatedRaw\x12$.bls_proto.VerifyAggregateRequestRaw\x1a\".bls_proto.VerifyAggregateResponse\x12_\n\x13VerifyAggregatedHex\x12$.bls_proto.VerifyAggregateRequestHex\x1a\".bls_proto.VerifyAggregateResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLSSIGNING._serialized_start=32
  _BLSSIGNING._serialized_end=868
# @@protoc_insertion_point(module_scope)
